name: Production DBT pipeline. Runs on schedule and when PR was merged to `main`.
on:
  push:
    branches: [ "main" ]
    paths:
      - 'dbt/**'
      - '.github/workflows/prod.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

  workflow_dispatch:

jobs:
  DBT:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-snowflake

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: DBT execution
        run: |
          cd dbt
          dbt deps
          dbt test
          dbt seed
          dbt run
        env:
          account: ${{ secrets.SF_ACCOUNT }}
          user: ${{ secrets.SF_USER }}
          password: ${{ secrets.SF_PASS }}
          role: sysadmin
          warehouse: wh_sfp
          database: mt_py
          schema: prod
          target: PROD
